"""
QueueTube — Git Delivery Module
================================
Takes code generated by code_agent.py and delivers it to the target repository
(queue-tube-web):

  1. Derives branch name from the source story issue
  2. Creates the branch from main HEAD — or reuses it on re-run (idempotent)
  3. Commits each generated file with a Conventional Commits message
  4. Creates a draft PR — or updates the existing one on re-run (idempotent)
  5. Applies labels: adds `code-draft` to PR + story issue, removes `code-ready`
  6. Writes a GitHub Actions step summary

Two repos are involved:
  SOURCE_REPO   — where branch/commit/PR land      (queue-tube-web)
  MCPS_REPO  — where the source story issue lives (queue-tube-mcps)

Token requirements:
  GH_PERSONAL_ACCESS_TOKEN — contents:write + pull-requests:write on SOURCE_REPO
  GITHUB_TOKEN                 — issues:write on MCPS_REPO (auto-provided by Actions)

Public API (called by code_agent.py):
  deliver(files, issue_number, issue_title, story_text, scope)
"""

import os
import re
import sys
import json
import base64
from pathlib import Path

import requests


# ── Configuration ─────────────────────────────────────────────────────────────

GITHUB_API_BASE = "https://api.github.com"
BRANCH_PREFIX = "feature/issue-"
SLUG_MAX_LEN = 40
BASE_BRANCH = "main"


# ── Environment ───────────────────────────────────────────────────────────────


def _get_env(name: str, default: str = "") -> str:
    return os.environ.get(name, default).strip()


def _require_env(name: str) -> str:
    value = _get_env(name)
    if not value:
        raise RuntimeError(
            f"Missing required environment variable: {name}. "
            "Set it before running this script."
        )
    return value


# ── Slug + branch name ────────────────────────────────────────────────────────


def slugify(title: str, max_len: int = SLUG_MAX_LEN) -> str:
    """
    Convert an issue title to a URL-safe branch slug.

    Rules:
    - Lowercase
    - Strip leading [Agent] prefix or [Story] prefix if present
    - Replace any non-alphanumeric character with a hyphen
    - Collapse consecutive hyphens
    - Strip leading/trailing hyphens
    - Truncate to max_len characters (never mid-word if avoidable)

    Pure function — no side effects, independently unit-testable.

    Examples:
      "Queue List Home Screen"          → "queue-list-home-screen"
      "[Story] Video Card (Filled State)" → "video-card-filled-state"
      "Empty state for queue with no videos" → "empty-state-for-queue-with-no-vi"
    """
    # Strip known agent/story prefixes
    text = re.sub(r"^\[(agent|story)\]\s*", "", title.strip(), flags=re.IGNORECASE)
    text = text.lower()
    text = re.sub(r"[^a-z0-9]+", "-", text)
    text = text.strip("-")
    # Truncate at max_len, preferring a word boundary
    if len(text) > max_len:
        truncated = text[:max_len]
        last_hyphen = truncated.rfind("-")
        if last_hyphen > max_len // 2:
            truncated = truncated[:last_hyphen]
        text = truncated.rstrip("-")
    return text


def derive_branch_name(issue_number: str | int, issue_title: str) -> str:
    """Return the canonical branch name for a story issue."""
    return f"{BRANCH_PREFIX}{issue_number}-{slugify(issue_title)}"


# ── GitHub REST helpers ───────────────────────────────────────────────────────


def _gh_headers(token: str) -> dict:
    return {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }


def get_main_sha(owner: str, repo: str, token: str) -> str:
    """Return the SHA of the HEAD commit on the base branch."""
    url = f"{GITHUB_API_BASE}/repos/{owner}/{repo}/git/ref/heads/{BASE_BRANCH}"
    resp = requests.get(url, headers=_gh_headers(token), timeout=15)
    if resp.status_code == 409:
        raise RuntimeError(
            f"Repository {owner}/{repo} is empty — no commits on '{BASE_BRANCH}' yet. "
            f"Push an initial commit to {owner}/{repo} before running the Code Sync agent. "
            f"(Complete issue #1 — Web Project Setup — first.)"
        )
    resp.raise_for_status()
    return resp.json()["object"]["sha"]


def branch_exists(owner: str, repo: str, branch: str, token: str) -> bool:
    """Return True if the branch already exists on the remote."""
    url = f"{GITHUB_API_BASE}/repos/{owner}/{repo}/git/ref/heads/{branch}"
    resp = requests.get(url, headers=_gh_headers(token), timeout=15)
    return resp.status_code == 200


def create_branch(owner: str, repo: str, branch: str, sha: str, token: str) -> None:
    """Create a new branch pointing at sha."""
    url = f"{GITHUB_API_BASE}/repos/{owner}/{repo}/git/refs"
    resp = requests.post(
        url,
        headers=_gh_headers(token),
        json={"ref": f"refs/heads/{branch}", "sha": sha},
        timeout=15,
    )
    resp.raise_for_status()
    print(f"✓ Branch created: {branch}")


def get_file_sha(
    owner: str, repo: str, path: str, branch: str, token: str
) -> str | None:
    """Return the blob SHA of an existing file, or None if the file does not exist."""
    url = f"{GITHUB_API_BASE}/repos/{owner}/{repo}/contents/{path}"
    resp = requests.get(
        url, headers=_gh_headers(token), params={"ref": branch}, timeout=15
    )
    if resp.status_code == 404:
        return None
    resp.raise_for_status()
    return resp.json().get("sha")


def commit_file(
    owner: str,
    repo: str,
    path: str,
    content: str,
    message: str,
    branch: str,
    token: str,
) -> None:
    """
    Create or update a single file on the branch via the GitHub Contents API.
    Automatically fetches the existing blob SHA when updating.
    """
    url = f"{GITHUB_API_BASE}/repos/{owner}/{repo}/contents/{path}"
    payload: dict = {
        "message": message,
        "content": base64.b64encode(content.encode("utf-8")).decode("ascii"),
        "branch": branch,
    }
    existing_sha = get_file_sha(owner, repo, path, branch, token)
    if existing_sha:
        payload["sha"] = existing_sha

    resp = requests.put(url, headers=_gh_headers(token), json=payload, timeout=30)
    resp.raise_for_status()
    verb = "Updated" if existing_sha else "Created"
    print(f"  ✓ {verb}: {path}")


# ── Commit message ────────────────────────────────────────────────────────────


def derive_scope(story_text: str) -> str:
    """
    Extract the primary component/screen name from the story text and convert it
    to a kebab-case commit scope.

    Heuristic: first PascalCase identifier found in the title line (or first 200
    chars) that looks like a component name.  Falls back to "agent" if nothing
    is found.
    """
    sample = story_text[:200]
    match = re.search(r"\b([A-Z][a-zA-Z0-9]{2,})\b", sample)
    if match:
        return re.sub(r"(?<!^)(?=[A-Z])", "-", match.group(1)).lower()
    return "agent"


def build_commit_message(
    scope: str,
    description: str,
    issue_number: str | int,
    is_rerun: bool = False,
) -> str:
    """
    Build a Conventional Commits message.

    First run:  feat(scope): description\n\nCloses #number
    Re-run:     fix(scope): description\n\nre: #number
    """
    prefix = "fix" if is_rerun else "feat"
    footer = f"re: #{issue_number}" if is_rerun else f"Closes #{issue_number}"
    return f"{prefix}({scope}): {description}\n\n{footer}"


# ── PR body ───────────────────────────────────────────────────────────────────


def _extract_acceptance_criteria(story_text: str) -> list[str]:
    """
    Pull `- [ ]` lines from the story text.
    Returns raw AC text strings (without the checkbox prefix).
    """
    return [
        m.group(1).strip()
        for m in re.finditer(r"-\s*\[\s*[xX ]?\s*\]\s*(.+)", story_text)
    ]


def build_pr_body(
    issue_number: str | int,
    issue_title: str,
    story_text: str,
    files_changed: list[str],
    notes: str = "",
) -> str:
    """
    Generate the structured PR body from the source story.

    Sections (in order):
      ## Source story
      ## Summary
      ## Files changed
      ## Testing checklist
      ## Notes for reviewer
    """
    # Extract one-liner ("As a … I want … So that …")
    summary_match = re.search(
        r"\*\*As a\*\*.*?\*\*So that\*\*[^\n]+", story_text, re.DOTALL
    )
    summary = summary_match.group(0).strip() if summary_match else "(see issue body)"

    # Build files-changed list
    files_section = (
        "\n".join(f"- `{f}`" for f in files_changed)
        if files_changed
        else "- *(no files listed)*"
    )

    # Build testing checklist from ACs
    acs = _extract_acceptance_criteria(story_text)
    checklist = (
        "\n".join(f"- [ ] {ac}" for ac in acs)
        if acs
        else "- [ ] Verify implementation matches acceptance criteria in the source story"
    )

    reviewer_notes = notes.strip() or "No additional assumptions made during code generation."

    return (
        f"## Source story\n\n"
        f"Closes #{issue_number} — {issue_title}\n\n"
        f"---\n\n"
        f"## Summary\n\n"
        f"{summary}\n\n"
        f"---\n\n"
        f"## Files changed\n\n"
        f"{files_section}\n\n"
        f"---\n\n"
        f"## Testing checklist\n\n"
        f"{checklist}\n\n"
        f"---\n\n"
        f"## Notes for reviewer\n\n"
        f"{reviewer_notes}\n\n"
        f"---\n"
        f"*Generated by the QueueTube Code Agent · Powered by Claude*"
    )


# ── Pull request ──────────────────────────────────────────────────────────────


def check_existing_pr(
    owner: str, repo: str, branch: str, token: str
) -> dict | None:
    """
    Return the first open PR for the given head branch, or None if none exists.
    Uses `head={owner}:{branch}` to match only PRs from this fork/owner.
    """
    url = f"{GITHUB_API_BASE}/repos/{owner}/{repo}/pulls"
    resp = requests.get(
        url,
        headers=_gh_headers(token),
        params={"head": f"{owner}:{branch}", "state": "open"},
        timeout=15,
    )
    resp.raise_for_status()
    prs = resp.json()
    return prs[0] if prs else None


def create_draft_pr(
    owner: str,
    repo: str,
    title: str,
    body: str,
    branch: str,
    token: str,
) -> dict:
    """Create a new draft PR and return the API response dict."""
    url = f"{GITHUB_API_BASE}/repos/{owner}/{repo}/pulls"
    resp = requests.post(
        url,
        headers=_gh_headers(token),
        json={
            "title": f"[Agent] {title}",
            "body": body,
            "head": branch,
            "base": BASE_BRANCH,
            "draft": True,
        },
        timeout=15,
    )
    resp.raise_for_status()
    pr = resp.json()
    print(f"✅ Draft PR created: #{pr['number']} — {pr['html_url']}")
    return pr


def update_pr(
    owner: str, repo: str, pr_number: int, body: str, token: str
) -> dict:
    """Update an existing PR's body and return the API response dict."""
    url = f"{GITHUB_API_BASE}/repos/{owner}/{repo}/pulls/{pr_number}"
    resp = requests.patch(
        url,
        headers=_gh_headers(token),
        json={"body": body},
        timeout=15,
    )
    resp.raise_for_status()
    pr = resp.json()
    print(f"✓ Draft PR updated: #{pr['number']} — {pr['html_url']}")
    return pr


# ── Labels ────────────────────────────────────────────────────────────────────


def add_label(owner: str, repo: str, issue_number: str | int, label: str, token: str) -> None:
    url = f"{GITHUB_API_BASE}/repos/{owner}/{repo}/issues/{issue_number}/labels"
    resp = requests.post(url, headers=_gh_headers(token), json={"labels": [label]}, timeout=15)
    resp.raise_for_status()
    print(f"✓ Label added to {repo}#{issue_number}: {label}")


def remove_label(
    owner: str, repo: str, issue_number: str | int, label: str, token: str
) -> None:
    url = f"{GITHUB_API_BASE}/repos/{owner}/{repo}/issues/{issue_number}/labels/{label}"
    resp = requests.delete(url, headers=_gh_headers(token), timeout=15)
    if resp.status_code not in (200, 204, 404):
        resp.raise_for_status()
    print(f"✓ Label removed from {repo}#{issue_number}: {label}")


# ── Step summary ──────────────────────────────────────────────────────────────


def write_step_summary(
    branch: str,
    pr_url: str,
    pr_number: int,
    is_new_branch: bool,
    is_new_pr: bool,
    files: list[str],
) -> None:
    """Write a GitHub Actions step summary. Silent when GITHUB_STEP_SUMMARY is absent."""
    summary_path = os.environ.get("GITHUB_STEP_SUMMARY")
    if not summary_path:
        return

    lines = [
        "## 🚀 Code Delivery — Summary\n",
        f"| | |",
        f"|---|---|",
        f"| **Branch** | `{branch}` ({'new' if is_new_branch else 'existing'}) |",
        f"| **Pull Request** | [#{pr_number}]({pr_url}) ({'created' if is_new_pr else 'updated'}) |",
        f"| **Files committed** | {len(files)} |",
        "",
    ]
    if files:
        lines.append("### Files\n")
        for f in files:
            lines.append(f"- `{f}`")
        lines.append("")

    with open(summary_path, "a", encoding="utf-8") as fh:
        fh.write("\n".join(lines))

    print("✓ Step summary written.")


# ── Public API ────────────────────────────────────────────────────────────────


def deliver(
    files: dict[str, str],
    issue_number: str | int,
    issue_title: str,
    story_text: str,
    scope: str | None = None,
    notes: str = "",
) -> dict:
    """
    Deliver generated code to the web app repository.

    Args:
        files:         Dict mapping file path → file content (UTF-8 strings).
        issue_number:  Source story issue number in queue-tube-mcps.
        issue_title:   Source story issue title.
        story_text:    Full story body (used for PR body and scope derivation).
        scope:         Commit scope override. If None, derived from story_text.
        notes:         Free-text notes for the PR "Notes for reviewer" section.

    Returns:
        Dict with keys: branch, pr_url, pr_number, is_new_branch, is_new_pr.

    Environment variables consumed:
        GH_PERSONAL_ACCESS_TOKEN  — write access to SOURCE_REPO
        GITHUB_TOKEN                  — issues:write on MCPS_REPO
        SOURCE_REPO                      — target repo (owner/repo, e.g. spreadcode-dev/queue-tube-web)
        MCPS_REPO                     — pipeline repo (owner/repo, e.g. spreadcode-dev/queue-tube-mcps)
    """
    print("── Git Delivery ────────────────────────────────────────────────")

    pat = _require_env("GH_PERSONAL_ACCESS_TOKEN")
    gh_token = _require_env("GITHUB_TOKEN")
    web_repo = _require_env("SOURCE_REPO")
    mcps_repo = _require_env("MCPS_REPO")

    web_owner, web_name = web_repo.split("/", 1)
    mcps_owner, mcps_name = mcps_repo.split("/", 1)

    resolved_scope = scope or derive_scope(story_text)
    branch = derive_branch_name(issue_number, issue_title)
    short_title = re.sub(r"^\[(agent|story)\]\s*", "", issue_title, flags=re.IGNORECASE).strip()

    # ── Step 1: Branch ────────────────────────────────────────────────────────
    is_new_branch = not branch_exists(web_owner, web_name, branch, pat)
    if is_new_branch:
        sha = get_main_sha(web_owner, web_name, pat)
        create_branch(web_owner, web_name, branch, sha, pat)
    else:
        print(f"✓ Branch already exists — reusing: {branch}")

    # ── Step 2: Detect re-run ─────────────────────────────────────────────────
    is_rerun = not is_new_branch

    # ── Step 3: Commit files ──────────────────────────────────────────────────
    if files:
        commit_msg = build_commit_message(
            resolved_scope,
            short_title.lower(),
            issue_number,
            is_rerun=is_rerun,
        )
        print(f"  Commit message: {commit_msg.splitlines()[0]}")
        for path, content in files.items():
            commit_file(web_owner, web_name, path, content, commit_msg, branch, pat)
    else:
        print("  ℹ️  No files to commit — branch created with no content.")

    # ── Step 4: Draft PR (idempotent) ─────────────────────────────────────────
    pr_body = build_pr_body(
        issue_number, short_title, story_text, list(files.keys()), notes
    )
    existing_pr = check_existing_pr(web_owner, web_name, branch, pat)
    is_new_pr = existing_pr is None

    if is_new_pr:
        pr = create_draft_pr(web_owner, web_name, short_title, pr_body, branch, pat)
    else:
        pr_number_existing = existing_pr["number"]
        print(f"✓ PR already exists — updating: #{pr_number_existing}")
        pr = update_pr(web_owner, web_name, pr_number_existing, pr_body, pat)

    # ── Step 5: Labels ────────────────────────────────────────────────────────
    add_label(mcps_owner, mcps_name, issue_number, "code-draft", gh_token)
    remove_label(mcps_owner, mcps_name, issue_number, "code-ready", gh_token)

    # ── Step 6: Step summary ──────────────────────────────────────────────────
    write_step_summary(
        branch=branch,
        pr_url=pr["html_url"],
        pr_number=pr["number"],
        is_new_branch=is_new_branch,
        is_new_pr=is_new_pr,
        files=list(files.keys()),
    )

    result = {
        "branch": branch,
        "pr_url": pr["html_url"],
        "pr_number": pr["number"],
        "is_new_branch": is_new_branch,
        "is_new_pr": is_new_pr,
    }
    print(f"✓ Delivery complete: {result}")
    print("────────────────────────────────────────────────────────────────")
    return result


# ── CLI / local test mode ─────────────────────────────────────────────────────


def _parse_args():
    import argparse

    parser = argparse.ArgumentParser(
        description=(
            "QueueTube Git Delivery — local test mode.\n\n"
            "Prints the derived branch name, commit message, and PR body "
            "without making any GitHub API calls."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("--issue-number", default="0", help="Story issue number.")
    parser.add_argument("--issue-title", default="Test story title", help="Story issue title.")
    parser.add_argument("--issue-body", default="", help="Story issue body (used for PR body).")
    parser.add_argument("--files", nargs="*", default=[], help="File paths to include in output.")
    return parser.parse_args()


def main() -> None:
    args = _parse_args()
    story_text = args.issue_body

    short_title = re.sub(r"^\[(agent|story)\]\s*", "", args.issue_title, flags=re.IGNORECASE).strip()
    branch = derive_branch_name(args.issue_number, args.issue_title)
    scope = derive_scope(story_text or short_title)
    commit_msg = build_commit_message(scope, short_title.lower(), args.issue_number)
    commit_msg_rerun = build_commit_message(
        scope, short_title.lower(), args.issue_number, is_rerun=True
    )
    pr_body = build_pr_body(
        args.issue_number, short_title, story_text, args.files or []
    )

    print("🚀 Git Delivery — local test mode (dry run, no API calls)\n")
    print(f"Branch name   : {branch}")
    print(f"Derived scope : {scope}")
    print(f"\nCommit (first run):\n{commit_msg}")
    print(f"\nCommit (re-run):\n{commit_msg_rerun}")
    print(f"\n{'='*64}\nPR Body:\n{'='*64}")
    print(pr_body)
    print("=" * 64)


if __name__ == "__main__":
    main()
